
INSERT INTO shop (id,name,phone_number,date_modified) VALUES (9,'Mo2men','16600','0000-00-00');

INSERT INTO meal (id,name,description,price,shop_id) VALUES (10,'Chicken Panee - Medium','',8.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (11,'Chicken Panee - Large','',12.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (12,'Chicken Panee - Combo Medium','',15.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (13,'Chicken Panee - Combo Large','',20.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (14,'Chicken Crispy - Medium','',8.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (15,'Chicken Crispy - Large','',12.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (16,'Chicken Crispy - Combo Medium','',15.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (17,'Chicken Crispy - Combo Large','',20.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (18,'Chicken Shawerma - Medium','',10.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (19,'Chicken Shawerma - Large','',12.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (20,'Chicken Shawerma - Combo Medium','',17.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (21,'Chicken Shawerma - Combo Large','',20.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (22,'Ala Greque - Medium','',11.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (23,'Ala Greque - Large','',13.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (24,'Ala Greque - Combo Medium','',18.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (25,'Ala Greque - Combo Large','',21.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (26,'Chicken Tender - Medium','',9.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (27,'Chicken Tender - Large','',11.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (28,'Chicken Tender - Combo Medium','',16.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (29,'Chicken Tender - Combo Large','',19.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (30,'Grand Roll - Medium','',12.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (31,'Grand Roll - Large','',17.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (32,'Grand Roll - Combo Medium','',19.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (33,'Grand Roll - Combo Large','',25.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (34,'Chicken Magnum - Medium','',12.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (35,'Chicken Magnum - Large','',18.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (36,'Chicken Magnum - Combo Medium','',19.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (37,'Chicken Magnum - Combo Large','',26.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (38,'Shish Tawook - Medium','',9.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (39,'Shish Tawook - Large','',12.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (40,'Shish Tawook - Combo Medium','',16.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (41,'Shish Tawook - Combo Large',' ',20.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (42,'Chicken Kiev - Medium','',11.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (43,'Chicken Kiev - Large','',13.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (44,'Chicken Kiev - Combo Medium','',18.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (45,'Chicken Kiev - Combo Large','',21.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (46,'Beef Shawerma - Medium','',8.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (47,'Beef Shawerma - Large','',12.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (48,'Beef Shawerma - Combo Medium','',15.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (49,'Beef Shawerma - Combo Large','',20.00,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (50,'Liver - Medium','',7.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (51,'Liver - Large','',9.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (52,'Liver - Combo Medium','',14.50,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (53,'Liver - Combo Large','',17.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (54,'Philly Cheese Steak - Medium','',10.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (55,'Philly Cheese Steak - Large','',14.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (56,'Philly Cheese Steak - Combo Medium','',17.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (57,'Philly Cheese Steak - Combo Large','',22.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (58,'Fried Shrimps - Medium','',11.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (59,'Fried Shrimps - Large','',15.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (60,'Fried Shrimps - Combo Medium','',18.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (61,'Fried Shrimps - Combo Large','',23.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (62,'Seafood Plus - Medium','',14.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (63,'Seafood Plus - Large','',17.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (64,'Seafood Plus - Combo Medium','',21.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (65,'Seafood Plus - Combo Large','',25.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (66,'Green Salad','',4.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (67,'Cole Slaw - Medium','',4.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (68,'Cole Slaw - Large','',6.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (69,'Seafood Salad','',11.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (70,'Potato Salad','',3.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (71,'French Fries - Medium','',5.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (72,'French Fries - Large','',6.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (73,'French Fries - King','',8.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (74,'Nougat','',6.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (75,'Chocolate & Crisp','',5.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (76,'Om Ali','',7.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (77,'Cheese Cake','',7.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (78,'Pepsi 400ml','',5.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (79,'Pepsi 500ml','',5.75,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (80,'Pepsi cans','',4.25,9);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (81,'Pepsi Family','',7.25,9);

--11-11-2008
INSERT INTO shop (id,name,phone_number,date_modified) VALUES (10,'Am Ahmad','5400144','0000-00-00');

INSERT INTO meal (id,name,description,price,shop_id) VALUES (82,'ﬂ”ﬂ”Ì','',3.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (83,'ﬂ”ﬂ”Ì »«·„ﬂ”—« ','',6.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (84,'ﬂ”ﬂ”Ì »«·ﬁ‘œ…','',6.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (85,'√—“ »«··»‰','',3.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (86,'√—“ »«··»‰ »«·⁄”·','',4.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (87,'√—“ »«··»‰ »«·„ﬂ”—« ','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (88,'√—“ »«··»‰ »«·ﬁ‘œ…','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (89,'√—“ »«··»‰ »«·ÃÌ·« Ì','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (90,'√—“ »«··»‰ »«·ÃÌ·« Ì Ê«·„ﬂ”—« ','',6.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (91,'⁄«‘Ê—… ','',3.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (92,'⁄«‘Ê—… »«·⁄”·','',4.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (93,'⁄«‘Ê—… »«·„ﬂ”—« ','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (94,'⁄«‘Ê—… »«·ﬁ‘œ…','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (95,'⁄«‘Ê—… »«·ÃÌ·« Ì','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (96,'⁄«‘Ê—… »«·ÃÌ·« Ì Ê«·„ﬂ”—« ','',6.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (98,'»·Ì·…','',3.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (99,'»·Ì·… »«·„ﬂ”—« ','',6.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (100,'»·Ì·… »«·ﬁ‘œ…','',6.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (101,'„‘„‘Ì…','',3.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (102,'„‘„‘Ì… »«·„ﬂ”—« ','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (103,'„‘„‘Ì… »«·ﬁ‘œ…','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (104,'„‘„‘Ì… »«·ÃÌ·« Ì','',5.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (105,'„‘„‘Ì… »«·ÃÌ·« Ì Ê«·„ﬂ”—« ','',6.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (106,'√„ ⁄·Ì','',6.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (107,'√„ ⁄·Ì »«·„ﬂ”—« ','',7.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (108,'√„ ⁄·Ì »«·ﬁ‘œ…','',7.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (109,'»Ê·… ¬Ì” ﬂ—Ì„','',2.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (110,'ﬂ√” ¬Ì” ﬂ—Ì„','',4.50,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (111,'ﬂ√” ¬Ì” ﬂ—Ì„ »«·„ﬂ”—« ','',6.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (112,'√„ ⁄·Ì ⁄„ √Õ„œ','',100.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (113,'› … »·Õ »«·ﬁ‘œ… Ê«·„ﬂ”—« ','',100.00,10);
INSERT INTO meal (id,name,description,price,shop_id) VALUES (115,'√—“ ›—‰ ⁄„ √Õ„œ','',100.00,10);

